export const WO_CONFIGMAPUNITGNOCNIMS_SEARCH = 'WO_CONFIGMAPUNITGNOCNIMS_SEARCH';
export const WO_CONFIGMAPUNITGNOCNIMS_GET_DETAIL = 'WO_CONFIGMAPUNITGNOCNIMS_GET_DETAIL';
export const WO_CONFIGMAPUNITGNOCNIMS_ADD = 'WO_CONFIGMAPUNITGNOCNIMS_ADD';
export const WO_CONFIGMAPUNITGNOCNIMS_EDIT = 'WO_CONFIGMAPUNITGNOCNIMS_EDIT';
export const WO_CONFIGMAPUNITGNOCNIMS_DELETE = 'WO_CONFIGMAPUNITGNOCNIMS_DELETE';
export const WO_CONFIGMAPUNITGNOCNIMS_GET_BUSINESS_NAME = ' WO_CONFIGMAPUNITGNOCNIMS_GET_BUSINESS_NAME';