export const UTILITY_SCOPESMANAGEMENT_SEARCH = 'UTILITY_SCOPESMANAGEMENT_SEARCH';
export const UTILITY_SCOPESMANAGEMENT_GET_DETAIL = 'UTILITY_SCOPESMANAGEMENT_GET_DETAIL';
export const UTILITY_SCOPESMANAGEMENT_ADD = 'UTILITY_SCOPESMANAGEMENT_ADD';
export const UTILITY_SCOPESMANAGEMENT_EDIT = 'UTILITY_SCOPESMANAGEMENT_EDIT';
export const UTILITY_SCOPESMANAGEMENT_DELETE = 'UTILITY_SCOPESMANAGEMENT_DELETE';