export const UTILITY_IMPACTSEGMENT_SEARCH = 'UTILITY_IMPACTSEGMENT_SEARCH';
export const UTILITY_IMPACTSEGMENT_GET_DETAIL = 'UTILITY_IMPACTSEGMENT_GET_DETAIL';
export const UTILITY_IMPACTSEGMENT_ADD = 'UTILITY_IMPACTSEGMENT_ADD';
export const UTILITY_IMPACTSEGMENT_EDIT = 'UTILITY_IMPACTSEGMENT_EDIT';
export const UTILITY_IMPACTSEGMENT_DELETE = 'UTILITY_IMPACTSEGMENT_DELETE';
export const UTILITY_IMPACTSEGMENT_EXPORT ='UTILITY_IMPACTSEGMENT_EXPORT';