export const WO_CONFIGPROPERTY_SEARCH = 'WO_CONFIGPROPERTY_SEARCH';
export const WO_CONFIGPROPERTY_GET_DETAIL = 'WO_CONFIGPROPERTY_GET_DETAIL';
export const WO_CONFIGPROPERTY_ADD = 'WO_CONFIGPROPERTY_ADD';
export const WO_CONFIGPROPERTY_EDIT = 'WO_CONFIGPROPERTY_EDIT';
export const WO_CONFIGPROPERTY_DELETE = 'WO_CONFIGPROPERTY_DELETE';