export const WO_MAPPROVINCECDGROUP_SEARCH = 'WO_MAPPROVINCECDGROUP_SEARCH';
export const WO_MAPPROVINCECDGROUP_GET_DETAIL = 'WO_MAPPROVINCECDGROUP_GET_DETAIL';
export const WO_MAPPROVINCECDGROUP_ADD = 'WO_MAPPROVINCECDGROUP_ADD';
export const WO_MAPPROVINCECDGROUP_EDIT = 'WO_MAPPROVINCECDGROUP_EDIT';
export const WO_MAPPROVINCECDGROUP_DELETE = 'WO_MAPPROVINCECDGROUP_DELETE';
export const WO_MAPPROVINCECDGROUP_GETLIST_PROVINCE = 'WO_MAPPROVINCECDGROUP_GETLIST_PROVINCE';