export const WO_MATERIALSCONFIG_SEARCH = 'WO_MATERIALSCONFIG_SEARCH';
export const WO_MATERIALSCONFIG_GET_DETAIL = 'WO_MATERIALSCONFIG_GET_DETAIL';
export const WO_MATERIALSCONFIG_ADD = 'WO_MATERIALSCONFIG_ADD';
export const WO_MATERIALSCONFIG_EDIT = 'WO_MATERIALSCONFIG_EDIT';
export const WO_MATERIALSCONFIG_DELETE = 'WO_MATERIALSCONFIG_DELETE';
export const WO_MATERIALSCONFIG_GETSERVICE_BYINFRATYPE = 'WO_MATERIALSCONFIG_GETSERVICE_BYINFRATYPE';
export const WO_MATERIALSCONFIG_GET_ACTIONLIST = 'WO_MATERIALSCONFIG_GET_ACTIONLIST';
export const WO_MATERIALSCONFIG_EXPORT = 'WO_MATERIALSCONFIG_EXPORT';