export const WO_CONFIGWOHELPVSMART_SEARCH = 'WO_CONFIGWOHELPVSMART_SEARCH';
export const WO_CONFIGWOHELPVSMART_GET_DETAIL = 'WO_CONFIGWOHELPVSMART_GET_DETAIL';
export const WO_CONFIGWOHELPVSMART_ADD = 'WO_CONFIGWOHELPVSMART_ADD';
export const WO_CONFIGWOHELPVSMART_EDIT = 'WO_CONFIGWOHELPVSMART_EDIT';
export const WO_CONFIGWOHELPVSMART_DELETE = 'WO_CONFIGWOHELPVSMART_DELETE';
export const WO_CONFIGWOHELPVSMART_GETLIST_SYSTEM = 'WO_CONFIGWOHELPVSMART_GETLIST_SYSTEM';
export const WO_CONFIGWOHELPVSMART_GETLIST_VSMART = 'WO_CONFIGWOHELPVSMART_GETLIST_VSMART';
export const ON_DOWNLOAD_FILE_TEMPLATE = 'ON_DOWNLOAD_FILE_TEMPLATE';
export const ON_DOWNLOAD_FILE_ATTACH = 'ON_DOWNLOAD_FILE_ATTACH';

