export const UTILITY_AFFECTEDLEVEL_SEARCH = 'UTILITY_AFFECTEDLEVEL_SEARCH';
export const UTILITY_AFFECTEDLEVEL_GET_DETAIL = 'UTILITY_AFFECTEDLEVEL_GET_DETAIL';
export const UTILITY_AFFECTEDLEVEL_ADD = 'UTILITY_AFFECTEDLEVEL_ADD';
export const UTILITY_AFFECTEDLEVEL_EDIT = 'UTILITY_AFFECTEDLEVEL_EDIT';
export const UTILITY_AFFECTEDLEVEL_DELETE = 'UTILITY_AFFECTEDLEVEL_DELETE';
export const UTILITY_AFFECTEDLEVEL_EXPORT ='UTILITY_AFFECTEDLEVEL_EXPORT';