export const UTILITY_GROUPUNIT_SEARCH = 'UTILITY_GROUPUNIT_SEARCH';
export const UTILITY_GROUPUNIT_GET_DETAIL = 'UTILITY_GROUPUNIT_GET_DETAIL';
export const UTILITY_GROUPUNIT_ADD = 'UTILITY_GROUPUNIT_ADD';
export const UTILITY_GROUPUNIT_EDIT = 'UTILITY_GROUPUNIT_EDIT';
export const UTILITY_GROUPUNIT_DELETE = 'UTILITY_GROUPUNIT_DELETE';
export const UTILITY_GROUPUNIT_EXPORT = 'UTILITY_GROUPUNIT_EXPORT';