export const TT_MESSAGECONFIG_SEARCH = 'TT_MESSAGECONFIG_SEARCH';
export const TT_MESSAGECONFIG_GET_DETAIL = 'TT_MESSAGECONFIG_GET_DETAIL';
export const TT_MESSAGECONFIG_ADD = 'TT_MESSAGECONFIG_ADD';
export const TT_MESSAGECONFIG_EDIT = 'TT_MESSAGECONFIG_EDIT';
export const TT_MESSAGECONFIG_DELETE = 'TT_MESSAGECONFIG_DELETE';
export const TT_MESSAGECONFIG_GETSMSUSER ='TT_MESSAGECONFIG_GETSMSUSER';
export const TT_MESSAGECONFIG_GETMAXLEVELID='TT_MESSAGECONFIG_GETMAXLEVELID'