export const UTILITY_CRIMPACTFRAME_SEARCH = 'UTILITY_CRIMPACTFRAME_SEARCH';
export const UTILITY_CRIMPACTFRAME_GET_DETAIL = 'UTILITY_CRIMPACTFRAME_GET_DETAIL';
export const UTILITY_CRIMPACTFRAME_ADD = 'UTILITY_CRIMPACTFRAME_ADD';
export const UTILITY_CRIMPACTFRAME_EDIT = 'UTILITY_CRIMPACTFRAME_EDIT';
export const UTILITY_CRIMPACTFRAME_DELETE = 'UTILITY_CRIMPACTFRAME_DELETE';