export const UTILITY_CRACTIONCODE_SEARCH = 'UTILITY_CRACTIONCODE_SEARCH';
export const UTILITY_CRACTIONCODE_GET_DETAIL = 'UTILITY_CRACTIONCODE_GET_DETAIL';
export const UTILITY_CRACTIONCODE_ADD = 'UTILITY_CRACTIONCODE_ADD';
export const UTILITY_CRACTIONCODE_EDIT = 'UTILITY_CRACTIONCODE_EDIT';
export const UTILITY_CRACTIONCODE_DELETE = 'UTILITY_CRACTIONCODE_DELETE';