export const UTILITY_CRCABUSERS_SEARCH = 'UTILITY_CRCABUSERS_SEARCH';
export const UTILITY_CRCABUSERS_GET_DETAIL = 'UTILITY_CRCABUSERS_GET_DETAIL';
export const UTILITY_CRCABUSERS_ADD = 'UTILITY_CRCABUSERS_ADD';
export const UTILITY_CRCABUSERS_EDIT = 'UTILITY_CRCABUSERS_EDIT';
export const UTILITY_CRCABUSERS_DELETE = 'UTILITY_CRCABUSERS_DELETE';
export const UTILITY_CRCABUSERS_GET_ALL_USER = 'UTILITY_CRCABUSERS_GET_ALL_USER';
export const UTILITY_CRCABUSERS_LIST_IMPACT = 'UTILITY_CRCABUSERS_LIST_IMPACT';