export const UTILITY_CONFIGCHILDARRAY_SEARCH = 'UTILITY_CONFIGCHILDARRAY_SEARCH';
export const UTILITY_CONFIGCHILDARRAY_GET_DETAIL = 'UTILITY_CONFIGCHILDARRAY_GET_DETAIL';
export const UTILITY_CONFIGCHILDARRAY_ADD = 'UTILITY_CONFIGCHILDARRAY_ADD';
export const UTILITY_CONFIGCHILDARRAY_EDIT = 'UTILITY_CONFIGCHILDARRAY_EDIT';
export const UTILITY_CONFIGCHILDARRAY_DELETE = 'UTILITY_CONFIGCHILDARRAY_DELETE';
export const UTILITY_CONFIGCHILDARRAY_GETLIST_IMPACTSEGMENT = 'UTILITY_CONFIGCHILDARRAY_GETLIST_IMPACTSEGMENT';