export const UTILITY_VERSIONCATALOG_SEARCH = 'UTILITY_VERSIONCATALOG_SEARCH';
export const UTILITY_VERSIONCATALOG_GET_DETAIL = 'UTILITY_VERSIONCATALOG_GET_DETAIL';
export const UTILITY_VERSIONCATALOG_ADD = 'UTILITY_VERSIONCATALOG_ADD';
export const UTILITY_VERSIONCATALOG_EDIT = 'UTILITY_VERSIONCATALOG_EDIT';