export const TT_CONFIGMOP_SEARCH = 'TT_CONFIGMOP_SEARCH';
export const TT_CONFIGMOP_GET_DETAIL = 'TT_CONFIGMOP_GET_DETAIL';
export const TT_CONFIGMOP_ADD = 'TT_CONFIGMOP_ADD';
export const TT_CONFIGMOP_EDIT = 'TT_CONFIGMOP_EDIT';
export const TT_CONFIGMOP_DELETE = 'TT_CONFIGMOP_DELETE';
export const TT_CONFIGMOP_GETGROUP ='TT_CONFIGMOP_GETGROUP';
export const TT_CONFIGMOP_GETARRAY ='TT_CONFIGMOP_GETARRAY';
