export const TT_CONFIGRECEIVEUNIT_SEARCH = 'TT_CONFIGRECEIVEUNIT_SEARCH';
export const TT_CONFIGRECEIVEUNIT_GET_DETAIL = 'TT_CONFIGRECEIVEUNIT_GET_DETAIL';
export const TT_CONFIGRECEIVEUNIT_ADD = 'TT_CONFIGRECEIVEUNIT_ADD';
export const TT_CONFIGRECEIVEUNIT_EDIT = 'TT_CONFIGRECEIVEUNIT_EDIT';
export const TT_CONFIGRECEIVEUNIT_DELETE = 'TT_CONFIGRECEIVEUNIT_DELETE';
export const TT_GET_LIST_CAT_ITEM = 'TT_GET_LIST_CAT_ITEM';