export const TT_INFOCONFIG_SEARCH = 'TT_INFOCONFIG_SEARCH';
export const TT_INFOCONFIG_GET_DETAIL = 'TT_INFOCONFIG_GET_DETAIL';
export const TT_INFOCONFIG_ADD = 'TT_INFOCONFIG_ADD';
export const TT_INFOCONFIG_EDIT = 'TT_INFOCONFIG_EDIT';
export const TT_INFOCONFIG_DELETE = 'TT_INFOCONFIG_DELETE';
export const TT_INFOCONFIG_GETLISTALARMGROUP = 'TT_INFOCONFIG_GETLISTALARMGROUP';