export const TT_CONFIGTIME_SEARCH = 'TT_CONFIGTIME_SEARCH';
export const TT_CONFIGTIME_GET_DETAIL = 'TT_CONFIGTIME_GET_DETAIL';
export const TT_CONFIGTIME_ADD = 'TT_CONFIGTIME_ADD';
export const TT_CONFIGTIME_EDIT = 'TT_CONFIGTIME_EDIT';
export const TT_CONFIGTIME_DELETE = 'TT_CONFIGTIME_DELETE';
export const TT_GETLIST_SUBCATEGORY = 'TT_GETLIST_SUBCATEGORY';