export const WO_ERRORCASEMANAGEMENT_SEARCH = 'WO_ERRORCASEMANAGEMENT_SEARCH';
export const WO_ERRORCASEMANAGEMENT_GET_DETAIL = 'WO_ERRORCASEMANAGEMENT_GET_DETAIL';
export const WO_ERRORCASEMANAGEMENT_ADD = 'WO_ERRORCASEMANAGEMENT_ADD';
export const WO_ERRORCASEMANAGEMENT_EDIT = 'WO_ERRORCASEMANAGEMENT_EDIT';
export const WO_ERRORCASEMANAGEMENT_DELETE = 'WO_ERRORCASEMANAGEMENT_DELETE';
export const WO_ERRORCASEMANAGEMENT_EXPORT ='WO_ERRORCASEMANAGEMENT_EXPORT';
export const WO_ERRORCASEMANAGEMENT_GETLIST_SERVICE='WO_ERRORCASEMANAGEMENT_GETLIST_SERVICE';