export const PT_CONFIG_SEARCH = 'PT_CONFIG_SEARCH';
export const PT_CONFIG_GET_DETAIL = 'PT_CONFIG_GET_DETAIL';
export const PT_CONFIG_ADD = 'PT_CONFIG_ADD';
export const PT_CONFIG_EDIT = 'PT_CONFIG_EDIT';
export const PT_CONFIG_DELETE = 'PT_CONFIG_DELETE';
export const PT_CONFIG_EXPORT = 'PT_CONFIG_EXPORT';
export const PT_CONFIG_GET_TIME = 'PT_CONFIG_GET_TIME';