export const UTILITY_LANGUAGECONFIG_SEARCH = 'UTILITY_LANGUAGECONFIG_SEARCH';
export const UTILITY_LANGUAGECONFIG_GET_DETAIL = 'UTILITY_LANGUAGECONFIG_GET_DETAIL';
export const UTILITY_LANGUAGECONFIG_ADD = 'UTILITY_LANGUAGECONFIG_ADD';
export const UTILITY_LANGUAGECONFIG_EDIT = 'UTILITY_LANGUAGECONFIG_EDIT';
export const UTILITY_LANGUAGECONFIG_DELETE = 'UTILITY_LANGUAGECONFIG_DELETE';