export const UTILITY_WORKLOGS_SEARCH = 'UTILITY_WORKLOGS_SEARCH';
export const UTILITY_WORKLOGS_GET_DETAIL = 'UTILITY_WORKLOGS_GET_DETAIL';
export const UTILITY_WORKLOGS_ADD = 'UTILITY_WORKLOGS_ADD';
export const UTILITY_WORKLOGS_EDIT = 'UTILITY_WORKLOGS_EDIT';
export const UTILITY_WORKLOGS_DELETE = 'UTILITY_WORKLOGS_DELETE';
export const UTILITY_WORKLOGS_GET_WORKLOG_TYPE = 'UTILITY_WORKLOGS_GET_WORKLOG_TYPE'