export const WO_UPDATESERVICEINFRA_SEARCH = 'WO_UPDATESERVICEINFRA_SEARCH';
export const WO_UPDATESERVICEINFRA_GET_DETAIL = 'WO_UPDATESERVICEINFRA_GET_DETAIL';
export const WO_UPDATESERVICEINFRA_ADD = 'WO_UPDATESERVICEINFRA_ADD';
export const WO_UPDATESERVICEINFRA_EDIT = 'WO_UPDATESERVICEINFRA_EDIT';
export const WO_UPDATESERVICEINFRA_GET_SERVICE = 'WO_UPDATESERVICEINFRA_GET_SERVICE';
export const WO_UPDATESERVICEINFRA_GET_ITEM_TECH = 'WO_UPDATESERVICEINFRA_GET_ITEM_TECH'