export const UTILITY_ROLESMANAGEMENT_SEARCH = 'UTILITY_ROLESMANAGEMENT_SEARCH';
export const UTILITY_ROLESMANAGEMENT_GET_DETAIL = 'UTILITY_ROLESMANAGEMENT_GET_DETAIL';
export const UTILITY_ROLESMANAGEMENT_ADD = 'UTILITY_ROLESMANAGEMENT_ADD';
export const UTILITY_ROLESMANAGEMENT_EDIT = 'UTILITY_ROLESMANAGEMENT_EDIT';
export const UTILITY_ROLESMANAGEMENT_DELETE = 'UTILITY_ROLESMANAGEMENT_DELETE';