const iconsMenu = {
  'GNOC_OD_MANAGEMENT' : 'fa fa-wrench',
  'OD_TYPE_MANAGEMENT' : 'fa fa-th-list',
  'OD_SCHEDULE_CREATE' : 'fa fa-calendar-plus-o',
  'OD_CONFIG_BUSINESS' : 'fa fa-gear',
  'OD_WORKFLOW_MANAGEMENT' : 'fa fa-table',

  'GNOC_PT_MANAGEMENT' : 'fa fa-wrench',
  'PT_PROBLEM' : 'fa fa-th-list',
  'PT_CONFIG_TIME_HANDLE_PROBLEM' : 'fa fa-gear',

  'GNOC_UTILITY' : 'fa fa-th-large',
  'UTILITY_VERSION_CATALOG' : 'fa fa-th-list',
  'UTILITY_STATUS_CONFIG' : 'fa fa-gear',
  'UTILITY_LANGUAGE_CONFIG' : 'fa fa-language',
  'UTILITY_CONFIG_SHIFT_HANDOVER' : 'fa fa-gear',
  'UTILITY_CONFIG_EMPLOYEE_DAY_OFF' : 'fa fa-gear',
  'UTILITY_CONFIG_REQUEST_SCHEDULE' : 'fa fa-gear',
  'UTILITY_CONFIG_EMPLOYEE_IMPACT' : 'fa fa-gear',
  'UTILITY_WORK_LOGS' : 'fa fa-gear',

  'GNOC_KEDB' : 'fa fa-wrench',
  'KEDB_MANAGEMENT' : 'fa fa-warning',

  'GNOC_TT_MANAGEMENT' : 'fa fa-wrench',
  'TT_TROUBLE' : 'fa fa-th-list',
  'TT_CONFIG_TIME' : 'fa fa-gear',
  'TT_CONFIG_RECEIVE_UNIT' : 'fa fa-gear',
  'TT_CONFIG_MOP' : 'fa fa-gear',
  'TT_MESSAGE_CONFIG' : 'fa fa-gear',
  'TT_INFO_CONFIG' : 'fa fa-gear',

  'GNOC_CR' : 'fa fa-wrench',
  'CR_MANAGEMENT' : 'fa fa-th-list',
  'CR_ALARM_SETTING' : 'fa fa-gear',
  'CR_GROUP_DEPARTMENT_CONFIG' : 'fa fa-gear',
  'CR_DEVICE_TYPE_MANAGEMENT' : 'fa fa-gear',
  'CR_SCOPES_MANAGEMENT' : 'fa fa-gear',
  'CR_ROLES_MANAGEMENT' : 'fa fa-gear',
  'CR_CONFIG_IMPACT_SEGMENT' : 'fa fa-gear',
  'CR_CONFIG_AFFECTED_LEVEL' : 'fa fa-gear',
  'CR_DEPARTMENTS_ROLES_MANAGEMENT' : 'fa fa-gear',
  'CR_DEPARTMENTS_SCOPES_MANAGEMENT' : 'fa fa-gear',
  'CR_ROLES_SCOPES_MANAGEMENT' : 'fa fa-gear',
  'CR_PROCESS_MANAGEMENT' : 'fa fa-gear',
  'CR_CONFIG_RETURN_ACTION' : 'fa fa-gear',
  'CR_CONFIG_WEBSERVICE_IMPORT' : 'fa fa-gear',
  'CR_CONFIG_TEMP_IMPORT' : 'fa fa-gear',
  'CR_IMPACT_FRAME' : 'fa fa-gear',
  'CR_ACTION_CODE' : 'fa fa-gear',
  'CR_CONFIG_CHILD_ARRAY' : 'fa fa-gear',
  'CR_GROUP_UNIT' : 'fa fa-gear',
  'CR_CAB_USERS' : 'fa fa-gear',

  'GNOC_WO_MANAGEMENTS' : 'fa fa-wrench',
  'WO_MANAGEMENT' : 'fa fa-th-list',
  'WO_ERROR_CASE_MANAGEMENT' : 'fa fa-th-list',
  'WO_MAP_PROVINCE_CD_GROUP' : 'fa fa-th-list',
  'WO_CD_GROUP_MANAGEMENT' : 'fa fa-th-list',
  'WO_TYPE_MANAGEMENT' : 'fa fa-th-list',
  'WO_MATERIALS_CONFIG' : 'fa fa-th-list',
  'WO_CONFIG_WO_HELP_VSMART' : 'fa fa-th-list',
  'WO_CONFIG_PROPERTY' : 'fa fa-th-list',
  'WO_UPDATE_SERVICE_INFRA' : 'fa fa-th-list',
  'WO_CONFIG_MAP_UNIT_GNOC_NIMS' : 'fa fa-th-list',

};

export default iconsMenu;
