export const UTILITY_STATUSCONFIG_SEARCH = 'UTILITY_STATUSCONFIG_SEARCH';
export const UTILITY_STATUSCONFIG_GET_DETAIL = 'UTILITY_STATUSCONFIG_GET_DETAIL';
export const UTILITY_STATUSCONFIG_ADD = 'UTILITY_STATUSCONFIG_ADD';
export const UTILITY_STATUSCONFIG_EDIT = 'UTILITY_STATUSCONFIG_EDIT';
export const UTILITY_STATUSCONFIG_DELETE = 'UTILITY_STATUSCONFIG_DELETE';
export const UTILITY_STATUSCONFIG_GET_STATE = 'UTILITY_STATUSCONFIG_GET_STATE';
export const UTILITY_STATUSCONFIG_GET_PROCESS = 'UTILITY_STATUSCONFIG_GET_PROCESS';