export const OD_CONFIG_BUSINESS_SEARCH = 'OD_CONFIG_BUSINESS_SEARCH';
export const OD_CONFIG_BUSINESS_GET_DETAIL = 'OD_CONFIG_BUSINESS_GET_DETAIL';
export const OD_CONFIG_BUSINESS_ADD = 'OD_CONFIG_BUSINESS_ADD';
export const OD_CONFIG_BUSINESS_EDIT = 'OD_CONFIG_BUSINESS_EDIT';
export const OD_CONFIG_BUSINESS_DELETE = 'OD_CONFIG_BUSINESS_DELETE';
export const OD_CONFIG_BUSINESS_ADD_EDIT_GET_OD_TYPE = 'OD_CONFIG_BUSINESS_ADD_EDIT_GET_OD_TYPE';